### ISSUE TITLE
Default trusted networks in main/config/configuration.yaml includes internet IP's

### ISSUE THREAD

**Issue by bitcoredotorg** [natekspencer/hacs-atmo#11]
Hello, it appears the default "trusted_networks" address configured in main/config/configuration.yaml  is "192.0.0.0/8", which includes quite a large range of active internet-routable IP addresses (more internet IP's than private IP's, in fact).  The private address range for the common home "192" network range is actually 192.168.0.0/16.  If your intent is to allow only "private" networks, you may wish to correct that, and also include the two other private blocks: 172.16.0.0/12 and 10.0.0.0/8.

See: https://en.wikipedia.org/wiki/Private_network

cheers, hope this helps, I'm interested in this integration!

**Comment by natekspencer** [comment]
Thanks, the configuration.yaml file is not for use in production and does not get included in the release. It's purely to enable easy login while developing so I don't have to enter a password each time.

**Comment by natekspencer** [comment]
It's been a while, and I can't remember how or which integration it was I was working on exactly, but I vaguely recall that I had the more restrictive trusted networks range before but was getting a 192.x (not 168) address that was forcing me to login manually while testing. I just expanded it to the full block since I wasn't worried about unauthorized access. I'm curious though, are you seeing an issue with the trusted networks?

**Comment by bitcoredotorg** [comment]
To answer your question about if I'm having an issue - no, but also I have to be honest: I've not even tried to use your integration yet.

I assume it connects to an atmo pro over bluetooth and is able to add that as a device to home assistant, but it's unclear how that all works, so I've not even bought one yet. It was exciting to see someone (you) have created an integration for it, and I admire the effort you've put into it thus far.
